tap "caskroom/cask"
tap "caskroom/fonts"
tap "caskroom/homebrew-versions"
tap "homebrew/services"

cask "atom-beta"
cask "docker-edge"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "slack"
cask "zoomus"

brew "fswatch"
brew "hub"
brew "jq"
brew "kubectx"
brew "kubernetes-cli"
brew "rbenv"
brew "watch"
