#!/bin/sh

set -e
set -x

cd $(dirname "$0")/..

ln -nfs "$(pwd)/bash/main.sh" ~/.profile
ln -nfs "$(pwd)/gitconfig" ~/.gitconfig

if [ ! -x /usr/local/bin/brew ]; then
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew bundle
